-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
	gender,
	SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id,
    purchase_amount,
    average_purchase_amount,
    discount_applied
FROM (
    SELECT
        customer_id,
        purchase_amount,
        discount_applied,
        -- The OVER() clause calculates the average without collapsing rows
        ROUND(AVG(purchase_amount) OVER(), 2) AS average_purchase_amount
    FROM customer
    WHERE discount_applied = 'Yes'
) t
WHERE purchase_amount > average_purchase_amount;

-- Q3. Which are the top 5 products with the highest review rating?
SELECT
	item_purchased,
	ROUND(AVG(review_rating::numeric), 2) AS average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between standard and express shipping.
SELECT
	shipping_type,
	ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type = 'Express' OR shipping_type = 'Standard'
GROUP BY shipping_type
ORDER BY AVG(purchase_amount);

-- Q5. Do subscribed customers spend more? Compare the average spend and total revenue
-- between subscribers and non-subscribers.
SELECT
	subscription_status,
	COUNT(customer_id),
	ROUND(AVG(purchase_amount), 2) AS average_spend,
	SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, average_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases wwith discounts applied?
SELECT 
    item_purchased,
    -- Calculate the percentage: (Discounted Count / Total Count) * 100
    ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)), 2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
SELECT
	customer_groups,
	COUNT(customer_groups) AS count_per_group
FROM
(
SELECT
	CASE
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS customer_groups
FROM customer
) t
GROUP BY customer_groups;

-- Q8. What are the top 3 most purchased products within each category?
SELECT 
    category,
    item_purchased,
    total_purchases
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        -- Rank products within each category based on purchase count
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) as item_rank
    FROM customer
    GROUP BY category, item_purchased
) t
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer (>5)'
        ELSE 'Occasional Buyer (<=5)'
    END AS customer_type,
    COUNT(*) AS total_customers,
    -- Calculate percentage who are subscribed
    ROUND(
        AVG(CASE WHEN subscription_status = 'Yes' THEN 1.0 ELSE 0.0 END) * 100, 
        2
    ) AS subscription_rate_percentage
FROM customer
GROUP BY 1;

-- Alternative answer to Q9
WITH stats AS (
    SELECT 
        CASE 
            WHEN previous_purchases > 5 THEN 'Repeat'
            ELSE 'Occasional'
        END AS group_name,
        AVG(CASE WHEN subscription_status = 'Yes' THEN 1.0 ELSE 0.0 END) AS p,
        COUNT(*) AS n
    FROM customer
    GROUP BY 1
)
SELECT 
    group_name,
    ROUND(p * 100, 2) AS subscription_rate,
    n AS sample_size,
    -- Calculate the Standard Error
    ROUND(SQRT((p * (1 - p)) / n) * 100, 4) AS standard_error
FROM stats;

-- Q10. What is the revenue contribution of each age group?
SELECT
	age_group,
	SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY SUM(purchase_amount) DESC;

SELECT 
	*
FROM customer




